# Generated by Django 5.2 on 2025-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdata',
            name='conductivity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='water_level',
            field=models.IntegerField(),
        ),
    ]
